"""Does the wake manifold have the topology of X or of X/G?

Neural distance between a position and its C2 (180-degree) image, relative to a random-pair
baseline, under axis (folded) vs full (not folded), across 5 independently trained networks per
condition (s2 arena). If the manifold is the glued fundamental domain, a position and its group
image should collapse toward the same point; if it is the raw arena, they should not.

Produces Report/data/fundamental_domain_isomap.csv (the multi-seed statistics; used SI Sec. 5,
main_best.tex/main.tex). The Isomap visualization (figS_fundamental_domain.pdf) is a one-off plot
built from a single-seed run of the same pipeline and is not regenerated by this script.

    PYTHONPATH=. python3 fundamental_domain_isomap.py --out ../Report/data/fundamental_domain_isomap.csv
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from project5_symmetry.analysis.run_spectrum import collect, model_from_checkpoint  # noqa: E402
from project5_symmetry.analysis.run_tda import position_means  # noqa: E402
from project5_symmetry.training.dataset import TrajectoryDataset  # noqa: E402

CKPT_ROOT = Path("/Volumes/Crucial X6/prnn_backup/checkpoints/hd_invariance")
N = 18


def c2_partner(cells):
    return np.stack([N + 1 - cells[:, 0], N + 1 - cells[:, 1]], axis=1)


def ratio_for(cond, hd_mode, seed, data_root, n_states):
    ckpt_path = CKPT_ROOT / cond / hd_mode / f'seed_{seed:02d}' / 'ckpt_final.pt'
    if not ckpt_path.exists():
        return None
    ck = torch.load(ckpt_path, map_location='cpu', weights_only=False)
    model = model_from_checkpoint(ck, torch.device('cpu'))
    ds = TrajectoryDataset(str(Path(data_root) / cond))
    hidden, pos = collect(model, ds, hd_mode, n_states, torch.device('cpu'), seed=seed)
    means, cells = position_means(hidden, pos)
    partner = c2_partner(cells)
    idx = {tuple(c): i for i, c in enumerate(cells)}
    rng = np.random.default_rng(seed)
    rand_idx = rng.permutation(len(cells))
    d_partner, d_random = [], []
    for i, c in enumerate(cells):
        j = idx.get(tuple(partner[i]))
        if j is not None and j != i:
            d_partner.append(np.linalg.norm(means[i] - means[j]))
        d_random.append(np.linalg.norm(means[i] - means[rand_idx[i]]))
    d_partner, d_random = np.array(d_partner), np.array(d_random)
    return {
        'condition': cond, 'hd_mode': hd_mode, 'seed': seed,
        'd_partner_mean': float(d_partner.mean()), 'd_random_mean': float(d_random.mean()),
        'ratio': float(d_partner.mean() / d_random.mean()), 'n_pairs': len(d_partner),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--data-root', required=True,
                    help='directory holding an s2/ trajectory dataset (generate with '
                         'SymmetryArena(symmetry_condition="s2") + generate_dataset, as in '
                         'experiments/run_ensemble_sweep.py:ensure_data)')
    ap.add_argument('--out', required=True)
    ap.add_argument('--n-states', type=int, default=20_000)
    ap.add_argument('--seeds', type=int, nargs='+', default=[0, 1, 2, 3, 4])
    a = ap.parse_args()
    torch.set_num_threads(4)

    rows = []
    for hd_mode in ('axis', 'full'):
        for seed in a.seeds:
            r = ratio_for('s2', hd_mode, seed, a.data_root, a.n_states)
            if r is None:
                print(f'  skip s2/{hd_mode}/seed{seed}: no checkpoint'); continue
            rows.append(r)
            print(f"  s2/{hd_mode}/seed{seed}: ratio={r['ratio']:.3f} "
                  f"(partner={r['d_partner_mean']:.3f}, random={r['d_random_mean']:.3f})")

    with open(a.out, 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0]))
        w.writeheader(); w.writerows(rows)
    print(f'wrote {a.out}')

    from scipy.stats import mannwhitneyu
    ax = [r['ratio'] for r in rows if r['hd_mode'] == 'axis']
    fu = [r['ratio'] for r in rows if r['hd_mode'] == 'full']
    if ax and fu:
        u = mannwhitneyu(ax, fu, alternative='less')
        print(f'axis ratios: {ax}')
        print(f'full ratios: {fu}')
        print(f'Mann-Whitney U (axis < full): U={u.statistic}, p={u.pvalue:.5f}')


if __name__ == '__main__':
    main()
